DjangoWebProjectVS2017/DjangoWebProjectVS2017/urls.py
"""
Definition of urls for DjangoWebProjectVS2017.
"""

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views

import app.forms
import app.views
import app.models

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about', app.views.about, name='about'),
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Log in',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^user/', app.views.user_new, name='user'),
    url(r'^users/', app.views.users_detail, name='users_detail'),
    url(r'^chart/(?P<question_id>\d+)/$', app.views.chart, name='chart'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^polls/add/', app.views.question_new, name='add'),
    url(r'^polls/choice_add/(?P<question_id>\d+)/$', app.views.choice_add, name='choice_add'),
    url(r'^(?P<question_id>\d+)/(?P<selected_choice_id>\d+)/results/$', app.views.results, name='results'),
    url(r'^polls/(?P<question_id>\d+)/$', app.views.detail, name='detail'),
    url(r'^polls/(?P<question_id>\d+)/vote/$', app.views.vote, name='vote'),
    url(r'^polls/', app.views.index, name='index'),
   
]

DjangoWebProjectVS2017/app/models.py
"""
Definition of models.
"""

from django.db import models
from django.db.models.fields import CharField
from django.db.models.fields import DateField

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    question_cat = models.CharField(max_length=200, default="Sin categorizar")
    pub_date = models.DateTimeField('date published')
    question_choices_total = models.IntegerField(default='0')

class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    correct_answer = models.BooleanField(default=False)

class User(models.Model):
    email = models.CharField(max_length=200)
    nombre = models.CharField(max_length=200)

DjangoWebProjectVS2017/app/templates/polls/choice_new.html
{% extends "app/layout.html" %}
{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ mensaje }}</h3>

<h1>Insertar una opción</h1>
        <form method="POST" class="post-form">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Save</button>
        </form>
<a href="{% url 'index' %}">Ver preguntas</a> 

{% endblock %}

DjangoWebProjectVS2017/app/templates/polls/detail.html
{% extends "app/layout.html" %}
{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<h3>Pregunta: {{ question.question_text }}</h3>
{% if error_message %}<p><strong style="color:red;"><b>{{ error_message }}</b></strong></p>{% endif %}
<form action="{% url 'vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
{% if request.user.is_authenticated %}
    <a href="{% url 'choice_add' question.id %}"><h3>Insertar Opciones</h3></a> 
    <a href="{% url 'chart' question.id %}"> <h3>Ver resultado de la votacion</h3> </a><br />
{% else %}
    <input type="submit" value="Vote" />
{% endif %}

</form>
{% endblock %}

DjangoWebProjectVS2017/app/templates/polls/grafico.html
{% extends "app/layout.html" %}
{% block content %}
<canvas id="myChart"></canvas> <br />
<a href="{% url 'index' %}"> Volver a las preguntas</a><br />
{% load i18n %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
<script>
    var options = {};
    var ctx = document.getElementById('myChart');
    var d = "{{dates}}".replace(/&quot;/g,"\"");
    var c = "{{counts}}".replace(/&quot;/g,"\"");
    var dates = JSON.parse( d );
    var counts = JSON.parse( c );
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: dates,
            datasets: [
                {
                    data: counts,
                    label: 'Choice',
                }
            ]},
         options: {
            scales: {
                yAxes: [{
                ticks: {
                beginAtZero: true
        }
      }]
    }
  }
    })
</script>
{% endblock %}

DjangoWebProjectVS2017/app/templates/polls/index.html
{% extends "app/layout.html" %}
{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<form method="post"> {% csrf_token %}
    <select name="filtro">
        {% for category in categories %}
            <option value="{{category.question_cat}}">{{category.question_cat}}</option>
        {% endfor %}
    </select>
    <button type="submit"> Filtrar </button>
</form>

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'detail' question.id %}">{{ question.question_text }} - {{ question.question_cat }}</a></li>
    {% endfor %}
    </ul>
  
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% if request.user.is_authenticated %}
<a href="{% url 'add' %}"><h2>Insertar pregunta</h2></a> 
{% endif %}

{% endblock %}

DjangoWebProjectVS2017/app/templates/polls/question_new.html
{% extends "app/layout.html" %}
{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<h1>Insertar una pregunta</h1>
        <form method="POST" class="post-form">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Save</button>
        </form>
<a href="{% url 'index' %}">Ver preguntas</a> 

{% endblock %}

DjangoWebProjectVS2017/app/templates/polls/results.html
{% extends "app/layout.html" %}
{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'chart' question.id %}"> Ver grafica</a><br />
<a href="{% url 'index' %}">Contestar otra pregunta?</a>

{% endblock %}

DjangoWebProjectVS2017/app/templates/polls/user_new.html
{% extends "app/layout.html" %}
{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<h1>Insertar un usuario</h1>
        <form method="POST" class="post-form">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Save</button>
        </form>
 

{% endblock %}

DjangoWebProjectVS2017/app/templates/polls/users.html
{% extends "app/layout.html" %}
{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

{% if latest_user_list %}
    <ul>
    {% for user in latest_user_list %}
        <li>{{ user.email}}</li>
    {% endfor %}
    </ul>
  
{% else %}
    <p>No users are available.</p>
{% endif %}

{% endblock %}